export const LIGHT_MODE_PRIMARY_COLOR_MAIN = '#1976d2';
export const LIGHT_MODE_PRIMARY_COLOR_LIGHT = '#42a5f5';
export const LIGHT_MODE_PRIMARY_COLOR_DARK = '#1565c0';

export const LIGHT_MODE_BACKGROUND_COLOR_PAPER = '#ccc';

export const DARK_MODE_PRIMARY_COLOR_MAIN = '#90caf9';
export const DARK_MODE_PRIMARY_COLOR_LIGHT = '#e3f2fd';
export const DARK_MODE_PRIMARY_COLOR_DARK = '#42a5f5';

export const DARK_MODE_BACKGROUND_COLOR_DEFAULT = '#282c35';
export const DARK_MODE_BACKGROUND_COLOR_PAPER = '#ccc';
